---
- hosts: copyfilestoubuntu
  gather_facts: false
  become: true

  tasks:
    - name: install python3-pip
      package:
        name: 
          - python3
          - pip
        state: present
    - name: copy folder contents
      ansible.builtin.copy:
        remote_src: false
        src: ./README.md
        dest: /data
